package is.idega.idegaweb.member.isi.block.reports.business;

import com.idega.user.business.UserGroupPlugInBusiness;


public interface WorkReportBusiness extends com.idega.business.IBOService,is.idega.idegaweb.member.business.MemberUserBusiness, UserGroupPlugInBusiness
{
 public boolean addWorkReportGroupToEntity(int p0,java.lang.String p1,int p2,com.idega.data.IDOEntity p3) throws java.rmi.RemoteException;
 public boolean addWorkReportGroupToEntity(int p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReportGroup p1,com.idega.data.IDOEntity p2) throws java.rmi.RemoteException;
 public boolean areAllWorkReportsTemporarelyReadOnly() throws java.rmi.RemoteException;
 public boolean changeWorkReportGroupOfEntity(int p0,java.lang.String p1,int p2,java.lang.String p3,int p4,com.idega.data.IDOEntity p5) throws java.rmi.RemoteException;
 public boolean changeWorkReportGroupOfEntity(int p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReportGroup p1,is.idega.idegaweb.member.isi.block.reports.data.WorkReportGroup p2,com.idega.data.IDOEntity p3) throws java.rmi.RemoteException;
 public boolean closeWorkReport(int p0) throws java.rmi.RemoteException;
 public void createOrUpdateLeagueWorkReportGroupsForYear(int p0) throws java.rmi.RemoteException;
 public is.idega.idegaweb.member.isi.block.reports.data.WorkReportBoardMember createWorkReportBoardMember(int p0,java.lang.String p1,is.idega.idegaweb.member.isi.block.reports.data.WorkReportGroup p2)throws javax.ejb.CreateException, java.rmi.RemoteException;
 public is.idega.idegaweb.member.isi.block.reports.data.WorkReportBoardMember createWorkReportBoardMember(int p0,com.idega.user.data.User p1,is.idega.idegaweb.member.isi.block.reports.data.WorkReportGroup p2)throws javax.ejb.CreateException, java.rmi.RemoteException;
 public boolean createWorkReportData(int p0) throws java.rmi.RemoteException;
 public is.idega.idegaweb.member.isi.block.reports.data.WorkReportDivisionBoard createWorkReportDivisionBoard(int p0,com.idega.user.data.Group p1,is.idega.idegaweb.member.isi.block.reports.data.WorkReportGroup p2)throws javax.ejb.CreateException, java.rmi.RemoteException;
 public is.idega.idegaweb.member.isi.block.reports.data.WorkReportMember createWorkReportMember(int p0,com.idega.user.data.User p1)throws javax.ejb.CreateException, java.rmi.RemoteException;
 public is.idega.idegaweb.member.isi.block.reports.data.WorkReportMember createWorkReportMember(int p0,java.lang.Integer p1)throws javax.ejb.CreateException, java.rmi.RemoteException;
 public is.idega.idegaweb.member.isi.block.reports.data.WorkReportMember createWorkReportMember(int p0,java.lang.String p1)throws javax.ejb.CreateException, java.rmi.RemoteException;
 public void deleteWorkReportAccountRecordsForReport(int p0) throws java.rmi.RemoteException;
 public void deleteWorkReportBoardMembersForReport(int p0) throws java.rmi.RemoteException;
 public void deleteWorkReportMembersForReport(int p0) throws java.rmi.RemoteException;
 public is.idega.idegaweb.member.isi.block.reports.data.WorkReportGroup findWorkReportGroupByNameAndYear(java.lang.String p0,int p1) throws java.rmi.RemoteException;
 public java.util.Collection getAllLeagueWorkReportGroupsForYear(int p0) throws java.rmi.RemoteException;
 public java.util.Collection getAllWorkReportBoardMembersForWorkReportId(int p0) throws java.rmi.RemoteException;
 public java.util.Collection getAllWorkReportDivisionBoardForWorkReportId(int p0) throws java.rmi.RemoteException;
 public java.util.Collection getAllWorkReportDivisionBoardForWorkReportIdAndYear(int p0,int p1) throws java.rmi.RemoteException;
 public java.util.Collection getAllWorkReportGroupsForYearAndType(int p0,java.lang.String p1) throws java.rmi.RemoteException;
 public java.util.List getAllWorkReportGroupsPrimaryKeysThatHaveMembers(int p0) throws java.rmi.RemoteException;
 public java.util.List getAllWorkReportGroupsPrimaryKeysWithNoMembers(int p0) throws java.rmi.RemoteException;
 public java.util.Collection getAllWorkReportMembersForWorkReportId(int p0) throws java.rmi.RemoteException;
 public java.util.Collection getAllWorkReportMembersForWorkReportIdAndWorkReportGroupId(int p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReportGroup p1) throws java.rmi.RemoteException;
 public java.util.Collection getAllWorkReportsForYear(int p0) throws java.rmi.RemoteException;
 public int getAmmountOfAccountRecordByWorkReportIdWorkReportGroupIdAndWorkReportAccountKeyId(int p0,int p1,int p2) throws java.rmi.RemoteException;
 public int getAmmountOfAccountRecordByWorkReportIdWorkReportGroupIdAndWorkReportAccountKeyName(int p0,int p1,java.lang.String p2) throws java.rmi.RemoteException;
 public int getCountOfFemaleMembersByWorkReport(is.idega.idegaweb.member.isi.block.reports.data.WorkReport p0) throws java.rmi.RemoteException;
 public int getCountOfFemaleMembersEqualOrOlderThanAgeAndByWorkReport(int p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReport p1) throws java.rmi.RemoteException;
 public int getCountOfFemaleMembersOfYoungerAgeAndByWorkReport(int p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReport p1) throws java.rmi.RemoteException;
 public int getCountOfFemalePlayersByWorkReport(is.idega.idegaweb.member.isi.block.reports.data.WorkReport p0) throws java.rmi.RemoteException;
 public int getCountOfFemalePlayersByWorkReportAndWorkReportGroup(is.idega.idegaweb.member.isi.block.reports.data.WorkReport p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReportGroup p1) throws java.rmi.RemoteException;
 public int getCountOfFemalePlayersEqualOrOlderThanAgeAndByWorkReport(int p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReport p1) throws java.rmi.RemoteException;
 public int getCountOfFemalePlayersEqualOrOlderThanAgeAndByWorkReportAndWorkReportGroup(int p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReport p1,is.idega.idegaweb.member.isi.block.reports.data.WorkReportGroup p2) throws java.rmi.RemoteException;
 public int getCountOfFemalePlayersOfEqualAgeAndByWorkReportAndWorkReportGroup(int p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReport p1,is.idega.idegaweb.member.isi.block.reports.data.WorkReportGroup p2) throws java.rmi.RemoteException;
 public int getCountOfFemalePlayersOfYoungerAgeAndByWorkReport(int p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReport p1) throws java.rmi.RemoteException;
 public int getCountOfFemalePlayersOfYoungerAgeAndByWorkReportAndWorkReportGroup(int p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReport p1,is.idega.idegaweb.member.isi.block.reports.data.WorkReportGroup p2) throws java.rmi.RemoteException;
 public int getCountOfMaleMembersByWorkReport(is.idega.idegaweb.member.isi.block.reports.data.WorkReport p0) throws java.rmi.RemoteException;
 public int getCountOfMaleMembersEqualOrOlderThanAgeAndByWorkReport(int p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReport p1) throws java.rmi.RemoteException;
 public int getCountOfMaleMembersOfYoungerAgeAndByWorkReport(int p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReport p1) throws java.rmi.RemoteException;
 public int getCountOfMalePlayersByWorkReport(is.idega.idegaweb.member.isi.block.reports.data.WorkReport p0) throws java.rmi.RemoteException;
 public int getCountOfMalePlayersByWorkReportAndWorkReportGroup(is.idega.idegaweb.member.isi.block.reports.data.WorkReport p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReportGroup p1) throws java.rmi.RemoteException;
 public int getCountOfMalePlayersEqualOrOlderThanAgeAndByWorkReport(int p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReport p1) throws java.rmi.RemoteException;
 public int getCountOfMalePlayersEqualOrOlderThanAgeAndByWorkReportAndWorkReportGroup(int p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReport p1,is.idega.idegaweb.member.isi.block.reports.data.WorkReportGroup p2) throws java.rmi.RemoteException;
 public int getCountOfMalePlayersOfEqualAgeAndByWorkReportAndWorkReportGroup(int p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReport p1,is.idega.idegaweb.member.isi.block.reports.data.WorkReportGroup p2) throws java.rmi.RemoteException;
 public int getCountOfMalePlayersOfYoungerAgeAndByWorkReport(int p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReport p1) throws java.rmi.RemoteException;
 public int getCountOfMalePlayersOfYoungerAgeAndByWorkReportAndWorkReportGroup(int p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReport p1,is.idega.idegaweb.member.isi.block.reports.data.WorkReportGroup p2) throws java.rmi.RemoteException;
 public int getCountOfMembersByWorkReport(is.idega.idegaweb.member.isi.block.reports.data.WorkReport p0) throws java.rmi.RemoteException;
 public int getCountOfMembersEqualOrOlderThanAgeAndByWorkReport(int p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReport p1) throws java.rmi.RemoteException;
 public int getCountOfMembersOfYoungerAgeAndByWorkReport(int p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReport p1) throws java.rmi.RemoteException;
 public int getCountOfPlayersByWorkReport(is.idega.idegaweb.member.isi.block.reports.data.WorkReport p0) throws java.rmi.RemoteException;
 public int getCountOfPlayersByWorkReportAndWorkReportGroup(is.idega.idegaweb.member.isi.block.reports.data.WorkReport p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReportGroup p1) throws java.rmi.RemoteException;
 public int getCountOfPlayersEqualOrOlderThanAgeAndByWorkReport(int p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReport p1) throws java.rmi.RemoteException;
 public int getCountOfPlayersEqualOrOlderThanAgeAndByWorkReportAndWorkReportGroup(int p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReport p1,is.idega.idegaweb.member.isi.block.reports.data.WorkReportGroup p2) throws java.rmi.RemoteException;
 public int getCountOfPlayersOfEqualAgeAndByWorkReportAndWorkReportGroup(int p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReport p1,is.idega.idegaweb.member.isi.block.reports.data.WorkReportGroup p2) throws java.rmi.RemoteException;
 public int getCountOfPlayersOfEqualAgeAndGenderByWorkReportAndWorkReportGroup(int p0,java.lang.String p1,is.idega.idegaweb.member.isi.block.reports.data.WorkReport p2,is.idega.idegaweb.member.isi.block.reports.data.WorkReportGroup p3) throws java.rmi.RemoteException;
 public int getCountOfPlayersOfYoungerAgeAndByWorkReport(int p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReport p1) throws java.rmi.RemoteException;
 public int getCountOfPlayersOfYoungerAgeAndByWorkReportAndWorkReportGroup(int p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReport p1,is.idega.idegaweb.member.isi.block.reports.data.WorkReportGroup p2) throws java.rmi.RemoteException;
 public java.lang.String getFileName(int p0) throws java.rmi.RemoteException;
 public java.util.Collection getLeaguesOfWorkReportById(int p0)throws com.idega.data.IDOException, java.rmi.RemoteException;
 public is.idega.idegaweb.member.isi.block.reports.data.WorkReportGroup getMainBoardWorkReportGroup(int p0) throws java.rmi.RemoteException;
 public int getOrCreateWorkReportIdForGroupIdByYear(int p0,int p1,boolean p2)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public int getTotalAmmountOfAccountRecordsByWorkReportIdWorkReportGroupIdAndWorkReportAccountKeyCollection(int p0,int p1,java.util.Collection p2) throws java.rmi.RemoteException;
 public int getTotalCountOfCompetitorsForWorkReportYear(int p0) throws java.rmi.RemoteException;
 public int getTotalCountOfMembersForWorkReportYear(int p0) throws java.rmi.RemoteException;
 public int getTotalCountOfPlayersForWorkReportYear(int p0) throws java.rmi.RemoteException;
 public int getTotalCountOfWorkReportsByStatusAndYear(java.lang.String p0,int p1) throws java.rmi.RemoteException;
 public is.idega.idegaweb.member.isi.block.reports.data.WorkReportAccountKeyHome getWorkReportAccountKeyHome() throws java.rmi.RemoteException;
 public is.idega.idegaweb.member.isi.block.reports.data.WorkReportBoardMemberHome getWorkReportBoardMemberHome() throws java.rmi.RemoteException;
 public is.idega.idegaweb.member.isi.block.reports.data.WorkReport getWorkReportById(int p0) throws java.rmi.RemoteException;
 public is.idega.idegaweb.member.isi.block.reports.data.WorkReportClubAccountRecordHome getWorkReportClubAccountRecordHome() throws java.rmi.RemoteException;
 public is.idega.idegaweb.member.isi.block.reports.data.WorkReportDivisionBoardHome getWorkReportDivisionBoardHome() throws java.rmi.RemoteException;
 public int getWorkReportExpensesByWorkReportIdAndWorkReportGroupId(int p0,int p1) throws java.rmi.RemoteException;
 public is.idega.idegaweb.member.isi.block.reports.data.WorkReportGroupHome getWorkReportGroupHome() throws java.rmi.RemoteException;
 public is.idega.idegaweb.member.isi.block.reports.data.WorkReportHome getWorkReportHome() throws java.rmi.RemoteException;
 public is.idega.idegaweb.member.isi.block.reports.data.WorkReportMemberHome getWorkReportMemberHome() throws java.rmi.RemoteException;
 public java.sql.Date getWorkReportOpenFromDate() throws java.rmi.RemoteException;
 public java.sql.Date getWorkReportOpenToDate() throws java.rmi.RemoteException;
 public java.lang.String getWorkReportSentText(int p0) throws java.rmi.RemoteException;
 public java.util.Collection getWorkReportsByYearRegionalUnionsAndClubs(int p0,java.util.Collection p1,java.util.Collection p2) throws java.rmi.RemoteException;
 public java.util.Collection getWorkReportsForRegionalUnionCollection(int p0,java.util.Collection p1) throws java.rmi.RemoteException;
 public com.idega.presentation.ui.DropdownMenu getYearDropdownMenu(int p0) throws java.rmi.RemoteException;
 public boolean isBoardMissingForDivisionWithMembersOrYearlyAccount(int p0) throws java.rmi.RemoteException;
 public boolean isThereAYearlyAccountForAnEmptyDivision(int p0) throws java.rmi.RemoteException;
 public boolean isWorkReportReadOnly(int p0) throws java.rmi.RemoteException;
 public boolean isYearlyAccountMissingForADivisionWithMembers(int p0) throws java.rmi.RemoteException;
 public boolean removeWorkReportGroupFromEntity(int p0,is.idega.idegaweb.member.isi.block.reports.data.WorkReportGroup p1,com.idega.data.IDOEntity p2) throws java.rmi.RemoteException;
 public boolean removeWorkReportGroupFromEntity(int p0,java.lang.String p1,int p2,com.idega.data.IDOEntity p3) throws java.rmi.RemoteException;
 public void removeWorkReportsTemporarelyReadOnlyFlag() throws java.rmi.RemoteException;
 public boolean sendWorkReport(int p0,java.lang.String p1,com.idega.idegaweb.IWResourceBundle p2)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public void setAllWorkReportsTemporarelyReadOnly() throws java.rmi.RemoteException;
 public void setAllWorkReportsTemporarelyReadOnlyFlag(boolean p0) throws java.rmi.RemoteException;
 public void setWorkReportOpenFromDateWithDateString(java.lang.String p0) throws java.rmi.RemoteException;
 public void setWorkReportOpenToDateWithDateString(java.lang.String p0) throws java.rmi.RemoteException;
 public boolean unSendWorkReport(int p0) throws java.rmi.RemoteException;
 public void updateWorkReportData(int p0)throws javax.ejb.FinderException,com.idega.data.IDOException,java.rmi.RemoteException, java.rmi.RemoteException;
}
