package is.idega.idegaweb.golf.entity;


public interface Tournament extends is.idega.idegaweb.golf.entity.GolfEntity
{
 public void delete()throws java.sql.SQLException;
 public void deleteAllData()throws java.sql.SQLException;
 public void deleteWithAllData()throws java.sql.SQLException;
 public java.sql.Timestamp getClosedDate();
 public java.sql.Timestamp getCreationDate();
 public int getDismissal(int p0)throws java.sql.SQLException;
 public int getDismissal(is.idega.idegaweb.golf.entity.Member p0)throws java.sql.SQLException;
 public java.sql.Timestamp getEndTime();
 public java.lang.String getExtraText();
 public float getFemaleMaxHandicap();
 public is.idega.idegaweb.golf.entity.Field getField()throws java.sql.SQLException;
 public int getFieldId();
 public java.sql.Timestamp getFirstRegistrationDate();
 public is.idega.idegaweb.golf.entity.Tournament[] getForthcomingTournaments()throws java.sql.SQLException;
 public boolean getIfGroupTournament();
 public boolean getIfOpenTournament();
 public boolean getIfRegistrationOnline();
 public int getInterval();
 public boolean getIsClosed();
 public java.sql.Timestamp getLastRegistrationDate();
 public float getMaxHandicap();
 public int getMinHandicap();
 public is.idega.idegaweb.golf.entity.Tournament[] getMostRecentTournaments(int p0)throws java.sql.SQLException;
 public java.lang.String getName();
 public int getNumberInGroup();
 public int getNumberOfDays();
 public int getNumberOfHoles();
 public int getNumberOfRounds();
 public int getPosition(is.idega.idegaweb.golf.entity.Member p0)throws java.sql.SQLException;
 public int getPosition(int p0)throws java.sql.SQLException;
 public int getRegistrationFee();
 public java.lang.String getRegistrationForm();
 public java.lang.String getRegistrationType();
 public java.sql.Timestamp getStartTime();
 public is.idega.idegaweb.golf.entity.TeeColor[] getTeeColors()throws java.sql.SQLException;
 public is.idega.idegaweb.golf.entity.TournamentDay[] getTournamentDays()throws java.sql.SQLException;
 public is.idega.idegaweb.golf.entity.TournamentForm getTournamentForm()throws java.sql.SQLException;
 public int getTournamentFormId();
 public int getTournamentGroupId(is.idega.idegaweb.golf.entity.Member p0)throws java.sql.SQLException;
 public int getTournamentGroupId(int p0)throws java.sql.SQLException;
 public is.idega.idegaweb.golf.entity.TournamentGroup[] getTournamentGroups()throws java.sql.SQLException;
 public int getTournamentMemberUnionId(java.sql.Connection p0,int p1)throws java.sql.SQLException;
 public int getTournamentMemberUnionId(int p0)throws java.sql.SQLException;
 public int getTournamentMemberUnionId(is.idega.idegaweb.golf.entity.Member p0)throws java.sql.SQLException;
 public is.idega.idegaweb.golf.entity.TournamentRound[] getTournamentRounds()throws java.sql.SQLException;
 public is.idega.idegaweb.golf.entity.TournamentType getTournamentType()throws java.sql.SQLException;
 public int getTournamentTypeId();
 public is.idega.idegaweb.golf.entity.Union getUnion()throws java.sql.SQLException;
 public int getUnionId();
 public boolean isDirectRegistration();
 public boolean isTournamentFinished();
 public boolean isTournamentOngoing();
 public void setClosedDate(java.sql.Timestamp p0);
 public void setCreationDate(java.sql.Timestamp p0);
 public void setDefaultValues();
 public void setDismissal(int p0,int p1)throws java.sql.SQLException;
 public void setDismissal(is.idega.idegaweb.golf.entity.Member p0,int p1)throws java.sql.SQLException;
 public void setEndTime(java.sql.Timestamp p0);
 public void setExtraText(java.lang.String p0);
 public void setField(is.idega.idegaweb.golf.entity.Field p0);
 public void setFieldId(java.lang.Integer p0);
 public void setFirstRegistrationDate(java.sql.Timestamp p0);
 public void setGroupTournament(boolean p0);
 public void setInterval(int p0);
 public void setIsClosed(boolean p0);
 public void setIsDirectRegistration(boolean p0);
 public void setLastRegistrationDate(java.sql.Timestamp p0);
 public void setMaxFemaleHandicap(float p0);
 public void setMaxHandicap(float p0);
 public void setMinHandicap(int p0);
 public void setName(java.lang.String p0);
 public void setNumberInGroup(int p0);
 public void setNumberOfDays(int p0);
 public void setNumberOfHoles(int p0);
 public void setNumberOfRounds(int p0);
 public void setOpenTournament(boolean p0);
 public void setPosition(int p0,int p1)throws java.sql.SQLException;
 public void setPosition(is.idega.idegaweb.golf.entity.Member p0,int p1)throws java.sql.SQLException;
 public void setRegistrationFee(int p0);
 public void setRegistrationForm(java.lang.String p0);
 public void setRegistrationOnline(boolean p0);
 public void setRegistrationType(java.lang.String p0);
 public void setStartTime(java.sql.Timestamp p0);
 public void setTournamentForm(is.idega.idegaweb.golf.entity.TournamentForm p0);
 public void setTournamentFormID(int p0);
 public void setTournamentType(is.idega.idegaweb.golf.entity.TournamentType p0);
 public void setTournamentTypeID(int p0);
 public void setUnion(is.idega.idegaweb.golf.entity.Union p0);
 public void setUnionId(java.lang.Integer p0);
 public void setUnionId(int p0);
}
