package se.idega.idegaweb.commune.childcare.business;

import java.rmi.RemoteException;

import com.idega.block.process.business.CaseBusiness;

public interface ChildCareBusiness extends com.idega.business.IBOService, CaseBusiness
{
 public boolean acceptApplication(se.idega.idegaweb.commune.childcare.data.ChildCareApplication p0,com.idega.util.IWTimestamp p1,java.lang.String p2,java.lang.String p3,com.idega.user.data.User p4) throws java.rmi.RemoteException;
 public boolean acceptApplication(int p0,com.idega.util.IWTimestamp p1,java.lang.String p2,java.lang.String p3,com.idega.user.data.User p4) throws java.rmi.RemoteException;
 public boolean assignApplication(int p0,com.idega.user.data.User p1,java.lang.String p2,java.lang.String p3) throws java.rmi.RemoteException;
 public boolean assignApplication(java.lang.String[] p0,com.idega.user.data.User p1,java.lang.String p2,java.lang.String p3) throws java.rmi.RemoteException;
 public boolean assignContractToApplication(java.lang.String[] p0,com.idega.user.data.User p1,java.util.Locale p2) throws java.rmi.RemoteException;
 public boolean assignContractToApplication(int p0,int p1,com.idega.util.IWTimestamp p2,com.idega.user.data.User p3,java.util.Locale p4,boolean p5) throws java.rmi.RemoteException;
 public boolean cancelContract(se.idega.idegaweb.commune.childcare.data.ChildCareApplication p0,boolean p1,com.idega.util.IWTimestamp p2,java.lang.String p3,java.lang.String p4,java.lang.String p5,com.idega.user.data.User p6) throws java.rmi.RemoteException;
 public void changePlacingDate(int p0,java.sql.Date p1,String p2)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public java.util.Collection findAllApplicationsWithChecksToRedeem() throws java.rmi.RemoteException;
 public java.util.Collection findAllGrantedApplications() throws java.rmi.RemoteException;
 public java.util.Collection getAcceptedApplicationsByProvider(int p0)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareApplication getApplication(int p0)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareApplication getApplicationByPrimaryKey(java.lang.String p0) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareApplication getApplicationForChildAndProvider(int p0,int p1)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public java.util.Collection getApplicationsByProvider(com.idega.user.data.User p0) throws java.rmi.RemoteException;
 public java.util.Collection getApplicationsByProvider(com.idega.block.school.data.School p0) throws java.rmi.RemoteException;
 public java.util.Collection getApplicationsByProvider(int p0) throws java.rmi.RemoteException;
 public java.util.Collection getOpenAndGrantedApplicationsByProvider(int p0) throws java.rmi.RemoteException;
 public java.util.Collection getApplicationsByUser(com.idega.user.data.User p0) throws java.rmi.RemoteException;
 public java.util.Collection getApplicationsForChild(com.idega.user.data.User p0) throws java.rmi.RemoteException;
 public java.util.Collection getApplicationsForChild(int childId) throws java.rmi.RemoteException; 
 public se.idega.idegaweb.commune.childcare.data.ChildCareContractHome getChildCareContractArchiveHome()throws java.rmi.RemoteException, java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCarePrognosisHome getChildCarePrognosisHome()throws java.rmi.RemoteException, java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareContract getContractFile(int p0)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public java.util.Collection getContractsByApplication(int p0)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public java.util.Collection getContractsByChild(int p0)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public java.util.Collection getContractsByChildAndProvider(int p0,int p1)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public java.util.Collection getGrantedApplicationsByUser(com.idega.user.data.User p0) throws java.rmi.RemoteException;
 public java.lang.String getLocalizedCaseDescription(com.idega.block.process.data.Case p0,java.util.Locale p1)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public se.idega.idegaweb.commune.message.business.MessageBusiness getMessageBusiness()throws java.rmi.RemoteException, java.rmi.RemoteException;
 public int getNumberInQueue(se.idega.idegaweb.commune.childcare.data.ChildCareApplication p0) throws java.rmi.RemoteException;
 public int getNumberInQueueByStatus(se.idega.idegaweb.commune.childcare.data.ChildCareApplication p0) throws java.rmi.RemoteException;
 public int getNumberOfApplicationsByProvider(int p0) throws java.rmi.RemoteException;
 public int getNumberOfApplicationsByProvider(int p0,int p1,java.sql.Date p2,java.sql.Date p3) throws java.rmi.RemoteException;
 public int getNumberOfUnhandledApplicationsByProvider(int p0) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCarePrognosis getPrognosis(int p0)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public int getQueueByArea(int p0)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public int getQueueByProvider(int p0)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public int getQueueTotalByArea(int p0)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public int getQueueTotalByProvider(int p0)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public com.idega.block.school.business.SchoolBusiness getSchoolBusiness()throws java.rmi.RemoteException, java.rmi.RemoteException;
 public char getStatusAccepted() throws java.rmi.RemoteException;
 public char getStatusCancelled() throws java.rmi.RemoteException;
 public char getStatusContract() throws java.rmi.RemoteException;
 public char getStatusParentsAccept() throws java.rmi.RemoteException;
 public char getStatusPriority() throws java.rmi.RemoteException;
 public char getStatusReady() throws java.rmi.RemoteException;
 public char getStatusSentIn() throws java.rmi.RemoteException;
 public char getStatusMoved() throws java.rmi.RemoteException;
 public char getStatusRejected() throws java.rmi.RemoteException;
 public char getStatusNewChoice() throws java.rmi.RemoteException;
 public char getStatusNotAnswered() throws java.rmi.RemoteException;
 public java.util.Collection getUnhandledApplicationsByProvider(com.idega.user.data.User p0) throws java.rmi.RemoteException;
 public java.util.Collection getUnhandledApplicationsByProvider(com.idega.block.school.data.School p0) throws java.rmi.RemoteException;
 public java.util.Collection getUnhandledApplicationsByProvider(int p0) throws java.rmi.RemoteException;
 public java.util.Collection getUnhandledApplicationsByProvider(int p0,int p1,int p2) throws java.rmi.RemoteException;
 public java.util.Collection getUnhandledApplicationsByProvider(int p0,int p1,int p2,int p3,java.sql.Date p4,java.sql.Date p5) throws java.rmi.RemoteException;
 public java.util.Collection getUnsignedApplicationsByProvider(com.idega.block.school.data.School p0) throws java.rmi.RemoteException;
 public java.util.Collection getUnsignedApplicationsByProvider(com.idega.user.data.User p0) throws java.rmi.RemoteException;
 public java.util.Collection getUnsignedApplicationsByProvider(int p0) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.business.CommuneUserBusiness getUserBusiness()throws java.rmi.RemoteException, java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.check.business.CheckBusiness getCheckBusiness() throws java.rmi.RemoteException;
 public java.lang.String getXMLContractPdfURL(com.idega.idegaweb.IWBundle p0,java.util.Locale p1) throws java.rmi.RemoteException;
 public java.lang.String getXMLContractTxtURL(com.idega.idegaweb.IWBundle p0,java.util.Locale p1) throws java.rmi.RemoteException;
 public boolean hasApplications(int childID) throws java.rmi.RemoteException;
 public boolean hasBeenPlacedWithOtherProvider(int p0,int p1)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public boolean insertApplications(com.idega.user.data.User p0,int[] p1,java.lang.String p2,int p3,int p4,java.lang.String p5,java.lang.String p6,boolean p7) throws java.rmi.RemoteException;
 public boolean insertApplications(com.idega.user.data.User p0,int[] p1,java.lang.String[] p2,String p3,int p4,int p5,java.lang.String p6,java.lang.String p7,boolean p8) throws java.rmi.RemoteException;
 public void moveToGroup(int p0,int p1,int p2)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public void parentsAgree(se.idega.idegaweb.commune.childcare.data.ChildCareApplication p0,com.idega.user.data.User p1,java.lang.String p2,java.lang.String p3)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public void parentsAgree(int p0,com.idega.user.data.User p1,java.lang.String p2,java.lang.String p3)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public boolean placeApplication(int p0,java.lang.String p1,java.lang.String p2,int p3,int p4,com.idega.user.data.User p5, java.util.Locale locale)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public boolean redeemApplication(java.lang.String p0,com.idega.user.data.User p1) throws java.rmi.RemoteException;
 public boolean rejectApplication(se.idega.idegaweb.commune.childcare.data.ChildCareApplication p0,java.lang.String p1,java.lang.String p2,java.lang.String p3,java.lang.String p4,com.idega.user.data.User p5) throws java.rmi.RemoteException;
 public boolean rejectApplication(int p0,java.lang.String p1,java.lang.String p2,java.lang.String p3,java.lang.String p4,com.idega.user.data.User p5) throws java.rmi.RemoteException;
 public boolean rejectOffer(int p0,com.idega.user.data.User p1) throws java.rmi.RemoteException;
 public boolean rejectOfferWithNewDate(int applicationId, com.idega.user.data.User user, java.sql.Date date) throws java.rmi.RemoteException;
 public void removeFromProvider(int p0,int p1,java.sql.Timestamp p2,boolean p3,java.lang.String p4)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public boolean removeFromQueue(se.idega.idegaweb.commune.childcare.data.ChildCareApplication p0,com.idega.user.data.User p1) throws java.rmi.RemoteException;
 public boolean removeFromQueue(int p0,com.idega.user.data.User p1) throws java.rmi.RemoteException;
 public void saveComments(int p0,java.lang.String p1)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public void setAsPriorityApplication(se.idega.idegaweb.commune.childcare.data.ChildCareApplication p0,java.lang.String p1,java.lang.String p2)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public void setAsPriorityApplication(int p0,java.lang.String p1,java.lang.String p2)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public void updatePrognosis(int p0,int p1,int p2, int threeMonthsPriority, int oneYearPriority)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public void sendMessageToProvider(se.idega.idegaweb.commune.childcare.data.ChildCareApplication application, String subject, String message, com.idega.user.data.User sender) throws java.rmi.RemoteException;
 public void sendMessageToParents(se.idega.idegaweb.commune.childcare.data.ChildCareApplication application, String subject, String body) ;
 public java.util.Collection getInactiveApplicationsByProvider(int providerID) throws java.rmi.RemoteException;
 public java.util.Map getProviderAreaMap(java.util.Collection schoolAreas, java.util.Locale locale, String emptyString) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareApplication getApplication(int childID, int choiceNumber) throws java.rmi.RemoteException;
 public java.util.Collection getQueueChoices(int childID) throws java.rmi.RemoteException;
 public int getPositionInQueue(se.idega.idegaweb.commune.childcare.data.ChildCareQueue queue) throws java.rmi.RemoteException;
 public boolean insertApplications(com.idega.user.data.User user, int provider[], String[] dates, String message, int checkId, int childId, String subject, String body, boolean freetimeApplication, boolean sendMessages, java.sql.Date[] queueDates, boolean[] hasPriority) throws java.rmi.RemoteException;
 public boolean insertApplications(com.idega.user.data.User user, int provider[], String[] dates, String message, int childID, java.sql.Date[] queueDates, boolean[] hasPriority) throws java.rmi.RemoteException;
 public void setChildCareQueueExported(se.idega.idegaweb.commune.childcare.data.ChildCareQueue queue) throws java.rmi.RemoteException;
 public boolean getHasUnexportedChoices(int childID);
 public void exportQueue(java.util.Collection choices) throws java.rmi.RemoteException;
 public int getOldQueueTotal(String[] queueType, boolean exported) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareContract getValidContract(int applicationID) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareContract getValidContract(int applicationID, java.sql.Date validDate) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareApplication getNonActiveApplication(int childID, int choiceNumber) throws java.rmi.RemoteException;
 public boolean retractOffer(se.idega.idegaweb.commune.childcare.data.ChildCareApplication application, String subject, String message, com.idega.user.data.User user) throws java.rmi.RemoteException;
 public boolean retractOffer(int applicationID, String subject, String message, com.idega.user.data.User user) throws java.rmi.RemoteException;
 public boolean reactivateApplication(se.idega.idegaweb.commune.childcare.data.ChildCareApplication application, com.idega.user.data.User user) throws java.rmi.RemoteException;
 public boolean reactivateApplication(int applicationID, com.idega.user.data.User user) throws java.rmi.RemoteException;
 public void convertOldQueue();
 public void addMissingGrantedChecks();
 public boolean hasActivePlacement(int childID) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareApplication getActivePlacement(int childID) throws java.rmi.RemoteException;
 public boolean hasUnansweredOffers(int childID) throws java.rmi.RemoteException;
 public boolean hasFutureContracts(int applicationID) throws java.rmi.RemoteException;
 public int getNumberOfFutureContracts(int applicationID) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareContract getValidContractByChild(int childID, java.sql.Date validDate) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareContract getValidContractByChild(int childID) throws java.rmi.RemoteException;
 public void removeFutureContracts(int applicationID, java.sql.Date date) throws java.rmi.RemoteException;
 public void removeFutureContracts(int applicationID) throws java.rmi.RemoteException;
 public boolean hasActivePlacementNotWithProvider(int childID, int providerID) throws java.rmi.RemoteException;
 public boolean hasTerminationInFutureNotWithProvider(int childID, int providerID) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareContract getLatestTerminatedContract(int childID) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareContract getLatestContract(int childID) throws java.rmi.RemoteException;
 public void alterValidFromDate(se.idega.idegaweb.commune.childcare.data.ChildCareApplication application, java.sql.Date newDate, java.util.Locale locale, com.idega.user.data.User user) throws java.rmi.RemoteException;
 public void alterValidFromDate(int applicationID, java.sql.Date newDate, java.util.Locale locale, com.idega.user.data.User user) throws java.rmi.RemoteException;
 public boolean hasActiveContract(int applicationID) throws java.rmi.RemoteException;
 public java.util.Collection getUnhandledApplicationsByChild(int childID) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareApplication getActiveApplicationByChild(int childID) throws java.rmi.RemoteException;
 public boolean hasActiveApplication(int childID) throws java.rmi.RemoteException;
 public boolean hasOutstandingOffers(int childID) throws java.rmi.RemoteException;
 public int getNumberOfApplicationsForChildByStatus(int childID, String caseStatus) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareApplication getAcceptedApplicationsByChild(int childID) throws java.rmi.RemoteException;
 public int getNumberOfApplicationsForChild(int childID) throws java.rmi.RemoteException;
 public int getNumberOfApplicationsForChildNotInactive(int childID) throws java.rmi.RemoteException;
 public int getNumberOfFirstHandChoicesByProvider(int providerID) throws java.rmi.RemoteException;
 public boolean importChildToProvider(int childID, int providerID, int groupID, int careTime, com.idega.util.IWTimestamp fromDate, com.idega.util.IWTimestamp toDate, java.util.Locale locale, com.idega.user.data.User parent, com.idega.user.data.User admin) throws java.rmi.RemoteException, se.idega.idegaweb.commune.block.importer.business.AlreadyCreatedException;
 public java.util.Collection getCaseLogNewContracts(java.sql.Timestamp fromDate, java.sql.Timestamp toDate) throws java.rmi.RemoteException;
 public java.util.Collection getCaseLogAlteredContracts(java.sql.Timestamp fromDate, java.sql.Timestamp toDate) throws java.rmi.RemoteException;
 public java.util.Collection getCaseLogTerminatedContracts(java.sql.Timestamp fromDate, java.sql.Timestamp toDate) throws java.rmi.RemoteException;
 public boolean canCancelContract(int applicationID) throws RemoteException;
 public int getNumberOfContractsForApplication(int applicationID) throws RemoteException;
}