package se.idega.idegaweb.commune.childcare.business;


public interface ChildCareBusiness extends com.idega.business.IBOService
{
 public boolean acceptApplication(se.idega.idegaweb.commune.childcare.data.ChildCareApplication p0,com.idega.util.IWTimestamp p1,java.lang.String p2,java.lang.String p3,com.idega.user.data.User p4) throws java.rmi.RemoteException;
 public boolean acceptApplication(int p0,com.idega.util.IWTimestamp p1,java.lang.String p2,java.lang.String p3,com.idega.user.data.User p4) throws java.rmi.RemoteException;
 public void addMissingGrantedChecks() throws java.rmi.RemoteException;
 public boolean alterContract(se.idega.idegaweb.commune.childcare.data.ChildCareContract p0,int p1,java.sql.Date p2,java.sql.Date p3,java.util.Locale p4,com.idega.user.data.User p5) throws java.rmi.RemoteException;
 public boolean alterContract(int p0,int p1,java.sql.Date p2,java.sql.Date p3,java.util.Locale p4,com.idega.user.data.User p5) throws java.rmi.RemoteException;
 public void alterValidFromDate(int p0,java.sql.Date p1,int p2,java.util.Locale p3,com.idega.user.data.User p4)throws java.rmi.RemoteException,se.idega.idegaweb.commune.childcare.business.NoPlacementFoundException, java.rmi.RemoteException;
 public void alterValidFromDate(se.idega.idegaweb.commune.childcare.data.ChildCareApplication p0,java.sql.Date p1,int p2,java.util.Locale p3,com.idega.user.data.User p4)throws java.rmi.RemoteException,se.idega.idegaweb.commune.childcare.business.NoPlacementFoundException, java.rmi.RemoteException;
 public boolean assignApplication(java.lang.String[] p0,com.idega.user.data.User p1,java.lang.String p2,java.lang.String p3) throws java.rmi.RemoteException;
 public boolean assignApplication(int p0,com.idega.user.data.User p1,java.lang.String p2,java.lang.String p3) throws java.rmi.RemoteException;
 public boolean assignContractToApplication(int p0,int p1,com.idega.util.IWTimestamp p2,int p3,com.idega.user.data.User p4,java.util.Locale p5,boolean p6) throws java.rmi.RemoteException;
 public boolean assignContractToApplication(java.lang.String[] p0,com.idega.user.data.User p1,java.util.Locale p2) throws java.rmi.RemoteException;
 public boolean canCancelContract(int p0) throws java.rmi.RemoteException;
 public boolean cancelContract(se.idega.idegaweb.commune.childcare.data.ChildCareApplication p0,boolean p1,com.idega.util.IWTimestamp p2,java.lang.String p3,java.lang.String p4,java.lang.String p5,com.idega.user.data.User p6) throws java.rmi.RemoteException;
 public boolean changeApplicationStatus(int p0,char p1,com.idega.user.data.User p2)throws java.lang.IllegalArgumentException, java.rmi.RemoteException;
 public boolean changeApplicationStatus(se.idega.idegaweb.commune.childcare.data.ChildCareApplication p0,char p1,com.idega.user.data.User p2)throws java.lang.IllegalArgumentException, java.rmi.RemoteException;
 public void changePlacingDate(int p0,java.sql.Date p1,java.lang.String p2) throws java.rmi.RemoteException;
 public void convertOldQueue() throws java.rmi.RemoteException;
 public void exportQueue(java.util.Collection p0) throws java.rmi.RemoteException;
 public java.util.Collection findAllApplicationsWithChecksToRedeem() throws java.rmi.RemoteException;
 public java.util.Collection findAllEmploymentTypes() throws java.rmi.RemoteException;
 public java.util.Collection findAllGrantedApplications() throws java.rmi.RemoteException;
 public java.util.Collection findUnhandledApplicationsNotInCommune() throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareApplication getAcceptedApplicationsByChild(int p0) throws java.rmi.RemoteException;
 public java.util.Collection getAcceptedApplicationsByProvider(int p0)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareApplication getActiveApplicationByChild(int p0) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareApplication getActivePlacement(int p0) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.business.AfterSchoolBusiness getAfterSchoolBusiness() throws java.rmi.RemoteException;
 public java.lang.String getAfterSchoolCareCaseCode() throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareApplication getApplication(int p0,int p1) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareApplication getApplication(int p0) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareApplication getApplicationByPrimaryKey(java.lang.String p0) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareApplication getApplicationForChildAndProvider(int p0,int p1) throws java.rmi.RemoteException;
 public java.util.Collection getApplicationsByProvider(com.idega.user.data.User p0) throws java.rmi.RemoteException;
 public java.util.Collection getApplicationsByProvider(com.idega.block.school.data.School p0) throws java.rmi.RemoteException;
 public java.util.Collection getApplicationsByProvider(int p0) throws java.rmi.RemoteException;
 public java.util.Collection getApplicationsByUser(com.idega.user.data.User p0) throws java.rmi.RemoteException;
 public java.util.Collection getApplicationsForChild(com.idega.user.data.User p0) throws java.rmi.RemoteException;
 public java.util.Collection getApplicationsForChild(int p0) throws java.rmi.RemoteException;
 public java.lang.String getBundleIdentifier() throws java.rmi.RemoteException;
 public java.util.Collection getCaseLogAlteredContracts(java.sql.Timestamp p0,java.sql.Timestamp p1)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public java.util.Collection getCaseLogNewContracts(java.sql.Timestamp p0,java.sql.Timestamp p1)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public java.util.Collection getCaseLogTerminatedContracts(java.sql.Timestamp p0,java.sql.Timestamp p1)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.check.business.CheckBusiness getCheckBusiness() throws java.rmi.RemoteException;
 public java.lang.String getChildCareCaseCode() throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareContractHome getChildCareContractArchiveHome() throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCarePrognosisHome getChildCarePrognosisHome() throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareQueueHome getChildCareQueueHome() throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareContract getContractFile(int p0) throws java.rmi.RemoteException;
 public java.util.Collection getContractsByApplication(int p0) throws java.rmi.RemoteException;
 public java.util.Collection getContractsByChild(int p0) throws java.rmi.RemoteException;
 public java.util.Collection getContractsByChildAndProvider(int p0,int p1) throws java.rmi.RemoteException;
 public java.util.Collection getGrantedApplicationsByUser(com.idega.user.data.User p0) throws java.rmi.RemoteException;
 public boolean getHasUnexportedChoices(int p0) throws java.rmi.RemoteException;
 public java.util.Collection getInactiveApplicationsByProvider(int p0) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareContract getLatestContract(int p0) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareContract getLatestTerminatedContract(int p0) throws java.rmi.RemoteException;
 public java.lang.String getLocalizedCaseDescription(com.idega.block.process.data.Case p0,java.util.Locale p1)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public se.idega.idegaweb.commune.message.business.MessageBusiness getMessageBusiness() throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareApplication getNewestApplication(int p0,java.sql.Date p1) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareApplication getNonActiveApplication(int p0,int p1)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public int getNumberInQueue(se.idega.idegaweb.commune.childcare.data.ChildCareApplication p0) throws java.rmi.RemoteException;
 public int getNumberInQueueByStatus(se.idega.idegaweb.commune.childcare.data.ChildCareApplication p0) throws java.rmi.RemoteException;
 public int getNumberOfApplicationsByProvider(int p0) throws java.rmi.RemoteException;
 public int getNumberOfApplicationsByProvider(int p0,int p1,java.sql.Date p2,java.sql.Date p3) throws java.rmi.RemoteException;
 public int getNumberOfApplicationsForChild(int p0) throws java.rmi.RemoteException;
 public int getNumberOfApplicationsForChildByStatus(int p0,java.lang.String p1,java.lang.String p2) throws java.rmi.RemoteException;
 public int getNumberOfApplicationsForChildByStatus(int p0,java.lang.String p1) throws java.rmi.RemoteException;
 public int getNumberOfApplicationsForChildNotInactive(int p0,java.lang.String p1)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public int getNumberOfApplicationsForChildNotInactive(int p0)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public int getNumberOfContractsForApplication(int p0) throws java.rmi.RemoteException;
 public int getNumberOfFirstHandChoicesByProvider(int p0) throws java.rmi.RemoteException;
 public int getNumberOfFutureContracts(int p0) throws java.rmi.RemoteException;
 public int getNumberOfUnhandledApplicationsByProvider(int p0) throws java.rmi.RemoteException;
 public int getOldQueueTotal(java.lang.String[] p0,boolean p1) throws java.rmi.RemoteException;
 public java.util.Collection getOpenAndGrantedApplicationsByProvider(int p0) throws java.rmi.RemoteException;
 public int getPositionInQueue(se.idega.idegaweb.commune.childcare.data.ChildCareQueue p0) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCarePrognosis getPrognosis(int p0) throws java.rmi.RemoteException;
 public java.util.Map getProviderAreaMap(java.util.Collection p0,java.util.Locale p1,java.lang.String p2,boolean p3) throws java.rmi.RemoteException;
 public int getQueueByArea(int p0) throws java.rmi.RemoteException;
 public int getQueueByProvider(int p0) throws java.rmi.RemoteException;
 public java.util.Collection getQueueChoices(int p0) throws java.rmi.RemoteException;
 public int getQueueTotalByArea(int p0)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public int getQueueTotalByProvider(int p0) throws java.rmi.RemoteException;
 public int getQueueTotalByProviderWithinMonths(int p0,int p1) throws java.rmi.RemoteException;
 public com.idega.block.school.business.SchoolBusiness getSchoolBusiness() throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.school.business.SchoolChoiceBusiness getSchoolChoiceBusiness() throws java.rmi.RemoteException;
 public char getStatusAccepted() throws java.rmi.RemoteException;
 public char getStatusCancelled() throws java.rmi.RemoteException;
 public char getStatusContract() throws java.rmi.RemoteException;
 public char getStatusDeleted() throws java.rmi.RemoteException;
 public char getStatusDenied() throws java.rmi.RemoteException;
 public char getStatusMoved() throws java.rmi.RemoteException;
 public char getStatusNewChoice() throws java.rmi.RemoteException;
 public char getStatusNotAnswered() throws java.rmi.RemoteException;
 public char getStatusParentsAccept() throws java.rmi.RemoteException;
 public char getStatusPriority() throws java.rmi.RemoteException;
 public char getStatusReady() throws java.rmi.RemoteException;
 public char getStatusRejected() throws java.rmi.RemoteException;
 public char getStatusSentIn() throws java.rmi.RemoteException;
 public java.util.Collection getUnhandledApplicationsByChild(int p0,java.lang.String p1) throws java.rmi.RemoteException;
 public java.util.Collection getUnhandledApplicationsByChild(int p0) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareApplication getUnhandledApplicationsByChildAndProvider(int p0,int p1)throws javax.ejb.FinderException, java.rmi.RemoteException;
 public java.util.Collection getUnhandledApplicationsByProvider(com.idega.user.data.User p0) throws java.rmi.RemoteException;
 public java.util.Collection getUnhandledApplicationsByProvider(com.idega.block.school.data.School p0) throws java.rmi.RemoteException;
 public java.util.Collection getUnhandledApplicationsByProvider(int p0) throws java.rmi.RemoteException;
 public java.util.Collection getUnhandledApplicationsByProvider(int p0,int p1,int p2) throws java.rmi.RemoteException;
 public java.util.Collection getUnhandledApplicationsByProvider(int p0,int p1,int p2,int p3,java.sql.Date p4,java.sql.Date p5) throws java.rmi.RemoteException;
 public java.util.Collection getUnsignedApplicationsByProvider(int p0) throws java.rmi.RemoteException;
 public java.util.Collection getUnsignedApplicationsByProvider(com.idega.block.school.data.School p0) throws java.rmi.RemoteException;
 public java.util.Collection getUnsignedApplicationsByProvider(com.idega.user.data.User p0) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.business.CommuneUserBusiness getUserBusiness() throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareContract getValidContract(int p0,java.sql.Date p1) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareContract getValidContract(int p0) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareContract getValidContractByChild(int p0) throws java.rmi.RemoteException;
 public se.idega.idegaweb.commune.childcare.data.ChildCareContract getValidContractByChild(int p0,java.sql.Date p1) throws java.rmi.RemoteException;
 public java.lang.String getXMLContractPdfURL(com.idega.idegaweb.IWBundle p0,java.util.Locale p1) throws java.rmi.RemoteException;
 public java.lang.String getXMLContractTxtURL(com.idega.idegaweb.IWBundle p0,java.util.Locale p1) throws java.rmi.RemoteException;
 public boolean hasActiveApplication(int p0) throws java.rmi.RemoteException;
 public boolean hasActiveApplication(int p0,java.lang.String p1) throws java.rmi.RemoteException;
 public boolean hasActiveContract(int p0) throws java.rmi.RemoteException;
 public boolean hasActivePlacement(int p0) throws java.rmi.RemoteException;
 public boolean hasActivePlacementNotWithProvider(int p0,int p1) throws java.rmi.RemoteException;
 public boolean hasApplications(int p0) throws java.rmi.RemoteException;
 public boolean hasBeenPlacedWithOtherProvider(int p0,int p1)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public boolean hasFutureContracts(int p0) throws java.rmi.RemoteException;
 public boolean hasOutstandingOffers(int p0,java.lang.String p1)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public boolean hasTerminationInFutureNotWithProvider(int p0,int p1) throws java.rmi.RemoteException;
 public boolean hasUnansweredOffers(int p0,java.lang.String p1)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public boolean importChildToProvider(int p0,int p1,int p2,int p3,int p4,int p5,int p6,java.lang.String p7,com.idega.util.IWTimestamp p8,com.idega.util.IWTimestamp p9,java.util.Locale p10,com.idega.user.data.User p11,com.idega.user.data.User p12)throws se.idega.idegaweb.commune.block.importer.business.AlreadyCreatedException, java.rmi.RemoteException;
 public boolean importChildToProvider(int p0,int p1,int p2,int p3,int p4,int p5,int p6,java.lang.String p7,com.idega.util.IWTimestamp p8,com.idega.util.IWTimestamp p9,java.util.Locale p10,com.idega.user.data.User p11,com.idega.user.data.User p12,boolean p13)throws se.idega.idegaweb.commune.block.importer.business.AlreadyCreatedException, java.rmi.RemoteException;
 public boolean importChildToProvider(int p0,int p1,int p2,int p3,int p4,int p5,int p6,java.lang.String p7,com.idega.util.IWTimestamp p8,com.idega.util.IWTimestamp p9,java.util.Locale p10,com.idega.user.data.User p11,com.idega.user.data.User p12,boolean p13,com.idega.util.IWTimestamp p14,java.lang.String p15,boolean p16,java.lang.String p17,boolean p18,java.lang.String p19)throws se.idega.idegaweb.commune.block.importer.business.AlreadyCreatedException, java.rmi.RemoteException;
 public boolean insertApplications(com.idega.user.data.User p0,int[] p1,java.lang.String p2,int p3,int p4,java.lang.String p5,java.lang.String p6,boolean p7) throws java.rmi.RemoteException;
 public boolean insertApplications(com.idega.user.data.User p0,int[] p1,java.lang.String[] p2,java.lang.String p3,int p4,java.sql.Date[] p5,boolean[] p6) throws java.rmi.RemoteException;
 public boolean insertApplications(com.idega.user.data.User p0,int[] p1,java.lang.String[] p2,java.lang.String p3,int p4,int p5,java.lang.String p6,java.lang.String p7,boolean p8) throws java.rmi.RemoteException;
 public boolean insertApplications(com.idega.user.data.User p0,int[] p1,java.lang.String[] p2,java.lang.String p3,int p4,int p5,java.lang.String p6,java.lang.String p7,boolean p8,boolean p9,java.sql.Date[] p10,boolean[] p11) throws java.rmi.RemoteException;
 public boolean isAfterSchoolApplication(int p0) throws java.rmi.RemoteException;
 public boolean isAfterSchoolApplication(com.idega.block.process.data.Case p0) throws java.rmi.RemoteException;
 public void moveToGroup(int p0,int p1,int p2) throws java.rmi.RemoteException;
 public void moveToGroup(int p0,int p1)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public void parentsAgree(se.idega.idegaweb.commune.childcare.data.ChildCareApplication p0,com.idega.user.data.User p1,java.lang.String p2,java.lang.String p3)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public void parentsAgree(int p0,com.idega.user.data.User p1,java.lang.String p2,java.lang.String p3)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public boolean placeApplication(int p0,java.lang.String p1,java.lang.String p2,int p3,int p4,int p5,int p6,com.idega.user.data.User p7,java.util.Locale p8) throws java.rmi.RemoteException;
 public boolean reactivateApplication(int p0,com.idega.user.data.User p1)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public boolean reactivateApplication(se.idega.idegaweb.commune.childcare.data.ChildCareApplication p0,com.idega.user.data.User p1)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public boolean redeemApplication(java.lang.String p0,com.idega.user.data.User p1) throws java.rmi.RemoteException;
 public boolean rejectApplication(se.idega.idegaweb.commune.childcare.data.ChildCareApplication p0,java.lang.String p1,java.lang.String p2,com.idega.user.data.User p3) throws java.rmi.RemoteException;
 public boolean rejectApplication(int p0,java.lang.String p1,java.lang.String p2,com.idega.user.data.User p3) throws java.rmi.RemoteException;
 public boolean rejectOffer(int p0,com.idega.user.data.User p1) throws java.rmi.RemoteException;
 public boolean rejectOfferWithNewDate(int p0,com.idega.user.data.User p1,java.sql.Date p2) throws java.rmi.RemoteException;
 public boolean removeContract(se.idega.idegaweb.commune.childcare.data.ChildCareContract p0,com.idega.user.data.User p1) throws java.rmi.RemoteException;
 public boolean removeContract(int p0,com.idega.user.data.User p1) throws java.rmi.RemoteException;
 public void removeFromProvider(int p0,java.sql.Timestamp p1,boolean p2,java.lang.String p3) throws java.rmi.RemoteException;
 public boolean removeFromQueue(int p0,com.idega.user.data.User p1) throws java.rmi.RemoteException;
 public boolean removeFromQueue(se.idega.idegaweb.commune.childcare.data.ChildCareApplication p0,com.idega.user.data.User p1) throws java.rmi.RemoteException;
 public void removeFutureContracts(int p0) throws java.rmi.RemoteException;
 public void removeFutureContracts(int p0,java.sql.Date p1) throws java.rmi.RemoteException;
 public boolean retractOffer(int p0,java.lang.String p1,java.lang.String p2,com.idega.user.data.User p3) throws java.rmi.RemoteException;
 public boolean retractOffer(se.idega.idegaweb.commune.childcare.data.ChildCareApplication p0,java.lang.String p1,java.lang.String p2,com.idega.user.data.User p3) throws java.rmi.RemoteException;
 public void saveComments(int p0,java.lang.String p1) throws java.rmi.RemoteException;
 public void sendMessageToParents(se.idega.idegaweb.commune.childcare.data.ChildCareApplication p0,java.lang.String p1,java.lang.String p2) throws java.rmi.RemoteException;
 public void sendMessageToProvider(se.idega.idegaweb.commune.childcare.data.ChildCareApplication p0,java.lang.String p1,java.lang.String p2)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public void sendMessageToProvider(se.idega.idegaweb.commune.childcare.data.ChildCareApplication p0,java.lang.String p1,java.lang.String p2,com.idega.user.data.User p3)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public void setAsPriorityApplication(se.idega.idegaweb.commune.childcare.data.ChildCareApplication p0,java.lang.String p1,java.lang.String p2)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public void setAsPriorityApplication(int p0,java.lang.String p1,java.lang.String p2)throws java.rmi.RemoteException, java.rmi.RemoteException;
 public void setChildCareQueueExported(se.idega.idegaweb.commune.childcare.data.ChildCareQueue p0) throws java.rmi.RemoteException;
 public void updateMissingPlacements() throws java.rmi.RemoteException;
 public void updatePrognosis(int p0,int p1,int p2,int p3,int p4) throws java.rmi.RemoteException;
}
